[package]
name = "osmcategorizer_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
osmpbf = "0.3"
geo = "0.30.0"
csv = "1.3.1"
anyhow = "1.0.97"
log = "0.4.27"
simple_logger = "5.0.0"
benchmark-rs = "0.1.1"
itertools = "0.14.0"